// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETD_F2020_Lab5.Models;

namespace NETD_F2020_Lab5.Migrations
{
    [DbContext(typeof(FakedexContext))]
    partial class FakedexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NETD_F2020_Lab5.Models.Fakemon", b =>
                {
                    b.Property<Guid>("DexNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TypeOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TypeTwo")
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("DexNumber");

                    b.ToTable("Fakemons");
                });

            modelBuilder.Entity("NETD_F2020_Lab5.Models.Stats", b =>
                {
                    b.Property<Guid>("StatsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("StatsId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("NETD_F2020_Lab5.Models.Stats", b =>
                {
                    b.HasOne("NETD_F2020_Lab5.Models.Fakemon", "Fakemon")
                        .WithOne("Statistics")
                        .HasForeignKey("NETD_F2020_Lab5.Models.Stats", "StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakemon");
                });

            modelBuilder.Entity("NETD_F2020_Lab5.Models.Fakemon", b =>
                {
                    b.Navigation("Statistics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
