namespace NETD_F2020_Lab5.Models
{
    public enum Nature
    {
        Lonely,
        Brave,
        Adamant,
        Naughty,
        Hardy,
        Bold,
        Relaxed,
        Impish,
        Lax,
        Docile,
        Timid,
        Hasty,
        Jolly,
        Naive,
        Serious,
        Modest,
        Mild,
        Quiet,
        Rash,
        Bashful,
        Calm,
        Gentle,
        Sassy,
        Careful,
        Quirky
    }
}